version: '3.8'

services:
  qfinbox-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: qfinbox-development
    ports:
      - "8888:8888"  # Jupyter Lab
      - "8000:8000"  # Additional service port
    volumes:
      - .:/app
      - qfinbox-notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app/src
    networks:
      - qfinbox-network
    restart: unless-stopped

  qfinbox-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qfinbox-production
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app/src
      - ENV=production
    networks:
      - qfinbox-network
    restart: unless-stopped

volumes:
  qfinbox-notebooks:

networks:
  qfinbox-network:
    driver: bridge
