name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip pip-tools

    - name: Update requirements
      run: |
        # Update production requirements
        pip-compile --upgrade --resolver=backtracking requirements-prod.in || echo "No .in file found, skipping pip-compile"

        # Check for security vulnerabilities
        pip install safety
        safety check --json > safety-report.json || echo "Safety check completed"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated dependency update"
        body: |
          ## Automated Dependency Update

          This PR contains automated updates to project dependencies.

          ### Changes:
          - Updated package versions to latest compatible versions
          - Security vulnerability check completed

          ### Review Checklist:
          - [ ] Check that tests still pass
          - [ ] Verify compatibility with new versions
          - [ ] Review any breaking changes in updated packages

          Generated by GitHub Actions on ${{ github.run_id }}
        branch: update-dependencies
        delete-branch: true
        labels: |
          dependencies
          automated
